---

- name: install plugins
  get_url:
    url: "{{ item }}"
    dest: /opt/sonarqube-{{ sonarqube_version }}/extensions/plugins/
    mode: 0644
  with_items: "{{ sonarqube_plugins }}"
  become: yes
  become_user: "{{ sonarqube_user }}"
  notify: restart_sonarqube
