---

- name: reload_systemd
  command: systemctl daemon-reload
  become: yes

- name: restart_sonarqube
  service:
    name: sonarqube
    state: restarted
    enabled: yes
  become: yes

- name: cleanup_sonarqube
  command: find /opt -maxdepth 1 -type d -name sonarqube-* -a ! -name sonarqube-{{ sonarqube_version }} -exec rm -rf "{}" \;
  become: yes
